FROM node:18-alpine

WORKDIR /app/backend

RUN apk add --no-cache dumb-init

COPY backend/package*.json ./
RUN npm ci --omit=dev --no-audit --no-fund || (echo "---- NPM LOGS ----" && ls -la /root/.npm/_logs || true && cat /root/.npm/_logs/* || true && exit 1)


COPY backend/ ./

RUN addgroup -g 1001 -S nodejs && \
    adduser -S nodejs -u 1001

USER nodejs

ENTRYPOINT ["dumb-init", "--"]

CMD ["node", "src/workers/index.js"]
